feign:
  okhttp:
    enable: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
  httpclient:
    max-connections: 1000

payment-service:
  url: http://localhost:8080
  timeout: 5000
  max-connections: 1000